config/routes.rb
Rails.application.routes.draw do

	root to: "restaurants#index"

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :restaurants, shallow: true do
  	resources :reviews do
  		resources :endorsements
  	end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	belongs_to :user
  has_many :reviews, dependent: :destroy
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "thumb/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :name, length: { minimum: 3 }, uniqueness: true

  def average_rating
  	return 'N/A' if reviews.none?
  	reviews.average(:rating)
  end
  
end 

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements
  validates :rating, inclusion: (1..5)

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews
  has_many :restaurants
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

	def create
		@review = Review.find(params[:review_id])
		@review.endorsements.create
		render json: { new_endorsement_count: @review.endorsements.count }
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
  	@restaurant = Restaurant.create(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end 

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if current_user.id == @restaurant.user_id
      @restaurant.update(restaurant_params)
      redirect_to '/restaurants'
    else
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if current_user.id == @restaurant.user_id
      @restaurant.destroy
      flash[:notice] = "Restaurant deleted successfully"
      redirect_to '/restaurants'
    else
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :image, :description)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def new
	  @restaurant = Restaurant.find(params[:restaurant_id])
	  @review = Review.new
	end

	def create
	  @restaurant = Restaurant.find(params[:restaurant_id])
	  params[:review][:user_id] = current_user.id
	  @restaurant.reviews.create(review_params)
	  redirect_to restaurants_path
	end

	def destroy
	 	@review = Review.find(params[:id])
		if !current_user || current_user.id != @review.user_id
			flash[:notice] = "You are not allowed to delete this review"
    	redirect_to '/restaurants'
    else
	    @review.destroy
	    flash[:notice] = "Review deleted successfully"
	    redirect_to '/restaurants'
    end
  end

	def review_params
	  params.require(:review).permit(:gripes, :rating, :user_id, :restaurant_id, :id)
	end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook.data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def star_rating(rating)
		return rating unless rating.respond_to?(:round)
		remainder = (5 - rating)
		'★' * rating.round + "☆" * remainder
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <meta charset="UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if user_signed_in? %>
		<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	<% else %>
    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
		<%= link_to "Sign in", new_user_session_path %>
		<%= link_to "Sign up", new_user_registration_path %>
	<% end %>
	<p class="notice"><%= flash[:notice] %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: { multipart: true } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<%= f.file_field :image %>
	<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= restaurant.name %></h2>
    <h3><%= restaurant.description %></h3>
    <%= image_tag restaurant.image.url(:thumb) %>
    <% if !current_user.nil? && restaurant.user_id == current_user.id %>
      <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
      <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <% end %>
    <h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
    <%= link_to "#{restaurant.name}", restaurant_path(restaurant) %>
    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
  <h3>Reviews for <%= restaurant.name %></h3>
      <% if restaurant.reviews.any? %>
        <ul>
          <% restaurant.reviews.each do |review| %>
            <li>
              <%= review.gripes %>, <strong><%= review.rating %></strong>/5
              <br>
              <% if !current_user.nil? && review.user_id == current_user.id %>
                <%= link_to "Delete review", review_path(review), method: :delete %>
              <% end %>
                <br>
              <%= link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link' %>
              <span class="endorsements_count"><%= review.endorsements.count %></span> endorsements
              <p>Posted <%= time_ago_in_words(review.created_at) %></p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No reviews.</p>
      <% end %>
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<% if user_signed_in? %>
  <a href="/restaurants/new">Add a restaurant</a>
<% else %>
<% end %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
	<section id="errors">
		<h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
		<ul>
			<% @restaurant.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</section>
<% end %>

<%= render "form" %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>
<h3>Reviews for <%= @restaurant.name %></h3>

<% if @restaurant.reviews.any? %>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.gripes %>, <strong><%= review.rating %></strong>/5
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews.</p>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :gripes %>
  <%= f.text_area :gripes %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>